name: Template de Plan/Apply/Destroy do Terraform

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Diretório onde estão os arquivos terraform"
        default: iac
        type: string
      action:
        description: "Escolha o que acontece no run deste workflow"
        type: string
        default: apply
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: "Role da AWS para OIDC"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    if: ${{ inputs.action == 'apply' }}
    uses: paulocesar-prog/linuxtips-terraform-reusable/.github/workflows/terraform-plan.yml@main
    with:
      working-directory: ${{ inputs.working-directory }}
    secrets: 
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  apply:
    needs: plan
    if: ${{ needs.plan.result == 'success' && inputs.action == 'apply' }}
    uses: paulocesar-prog/linuxtips-terraform-reusable/.github/workflows/terraform-apply.yml@main
    with:
      working-directory: ${{ inputs.working-directory }}
    secrets: 
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  destroy:
    if: ${{ inputs.action == 'destroy' }}
    uses: paulocesar-prog/linuxtips-terraform-reusable/.github/workflows/terraform-destroy.yml@main
    with:
      working-directory: ${{ inputs.working-directory }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}